var Localization = [];
var LocalizationToast = [];
switch($("#LanguageSelectBox").val())
{
    case "de":
        var monthShortName = ["Jan.", "Feb.", "M\u00e4rz", "Apr.", "Mai", "Juni", "Juli", "Aug.", "Sep.", "Okt.", "Nov.", "Dez."];
        /////Month translation////
        Localization["January"] = "Januar";
        Localization["February"] = "Februar";
        Localization["March"] = "März";
        Localization["April"] = "April";
        Localization["May"] = "Mai";
        Localization["June"] = "Juni";
        Localization["July"] = "Juli";
        Localization["August"] = "August";
        Localization["September"] = "September";
        Localization["October"] = "Oktober";
        Localization["November"] = "November";
        Localization["December"] = "Dezember";
        /////Month translation////
        Localization["About"] = "Über uns";
        Localization["Add/Edit Customer"] = "Kunden";
        Localization["Add/Edit Technician"] = "Techniker";
        Localization["Add/Edit Ticket"] = "Ticket";
        Localization["Analytics"] = "Analytik";
        Localization["Assigned"] = "zugewiesen";
        Localization["Canceled"] = "Abgebrochen";
        Localization["Closed"] = "Geschlossen";
        Localization["ConfirmDeleteAgent"] = "Sind Sie sicher, dass Sie das Agent löschen möchten ";
        Localization["ConfirmDeleteTicket"] = "Sind Sie sicher, dass Sie das Ticket löschen möchten ";
        Localization["ConfirmDeleteTechnician"] = "Sind Sie sicher, dass Sie das Ticket löschen Techniker ";
        Localization["ConfirmResetPassordTechnician"] = "Möchten Sie das Techniker-Passwort wirklich zurücksetzen ";
        Localization["ConfirmDeleteCustomer"] = "Sind Sie sicher, dass Sie das Ticket löschen Kunden ";
        Localization["Contacts"] = "Kontakt";
        Localization["Customers"] = "Kunden";
        Localization["Dashboard"] = "Übersicht";
        Localization["doLoginInvalidCredentials"] = "Falscher Benutzername oder Passwort!";
        Localization["Female"] = "Weiblich";
        Localization["Functional Issues"] = "funktional Problem";
        Localization["High"] = "Hoch";
        Localization["House Holder"] = "Hauseigentümer";
        Localization["In_Process"] = "In Bearbeitung";
        Localization["In Process"] = "In Bearbeitung";
        Localization["Inbox"] = "Inbox";
        Localization["Login Page"] = "Login Page";
        Localization["Low"] = "Niedrig";
        Localization["Male"] = "Männlich";
        Localization["Mr."] = "Herr";
        Localization["Mrs."] = "Frau";
        Localization["New"] = "Neu";
        Localization["Normal"] = "Normal";
        Localization["Others"] = "sonstiges";
        Localization["Pause"] = "Pause";
        Localization["Parked"] = "Geparkt";
        Localization["Re-Opened"] = "Wiedereröffnete ";
        Localization["Resident"] = "Bewohner des Hauses";
        Localization["Resolved"] = "Abgeschlossen";
        Localization["Resume"] = "Fortsetzen";
        Localization["Several Houses"] = "Mehrere Häuser";
        Localization["Single Room"] = "Einzelwohnung";
        Localization["Tecnical Issues"] = "Technisches Problem";
        Localization["Technicians"] = "Techniker";
        Localization["Technician Detail"] = "Techniker";
        Localization["Technician Ticket"] = "Techniker";
        Localization["Third Party"] = "Firmen";
        Localization["Third Party Resident"] = "Firmen Endkunde";
        Localization["Ticket Detail"] = "Ticket";
        Localization["Tickets/Issues"] = "Tickets";
        Localization["Total Resolved Tickets"] = "Gesamtanzahl abgeschlossener Tickets";
        Localization["Total Tickets"] = "Gesamtanzahl der Tickets";
        Localization["User Profile"] = "User Profile";
        Localization["Whole House"] = "Ganzes Haus";
        //Ticket Categories///
        Localization["SignalDisplay"] = "NE 2 - Signalerstellung";
        Localization["SignalFeed"] = "NE 3 - Signalzuführung";
        Localization["CableSystem"] = "NE 4 - Kabelanlage";
        Localization["EndCustomer"] = "NE 5 - Endkunde";
        //analytic//
        Localization["This Month"] = "Diesen Monat";
        Localization["Last Month"] = "Letzten Monat";
        Localization["This Year"] = "Dieses Jahr";
        Localization["Last Year"] = "Letztes Jahr";

        Localization["Company"] = "Firma";
        break;
    default:
        var monthShortName = ["Jan.", "Feb.", "March", "Apr.", "Mai", "Jun", "July", "Aug.", "Sep.", "Oct.", "Nov.", "Dec."];
        /////Month translation////
        Localization["January"] = "January";
        Localization["February"] = "February";
        Localization["March"] = "March";
        Localization["April"] = "April";
        Localization["May"] = "May";
        Localization["June"] = "June";
        Localization["July"] = "July";
        Localization["August"] = "August";
        Localization["September"] = "September";
        Localization["October"] = "October";
        Localization["November"] = "November";
        Localization["December"] = "December";
        /////Month translation////
        Localization["About"] = "About";
        Localization["Add/Edit Customer"] = "Add/Edit Customer";
        Localization["Add/Edit Technician"] = "Add/Edit Technician";
        Localization["Add/Edit Ticket"] = "Add/Edit Ticket";
        Localization["Analytics"] = "Analytics";
        Localization["Assigned"] = "Assigned";
        Localization["Canceled"] = "Cancelled";
        Localization["Closed"] = "Closed";
        Localization["ConfirmDeleteAgent"] = "Are you sure you want to delete agent ";
        Localization["ConfirmDeleteTicket"] = "Are you sure you want to delete ticket ";
        Localization["ConfirmDeleteTechnician"] = "Are you sure you want to delete technician ";
        Localization["ConfirmResetPassordTechnician"] = "Are you sure you want to Reset technician password ";
        Localization["ConfirmDeleteCustomer"] = "Are you sure you want to delete customer ";
        Localization["Contacts"] = "Contacts";
        Localization["Customers"] = "Customers";
        Localization["Dashboard"] = "Dashboard";
        Localization["doLoginInvalidCredentials"] = "Invalid User Name or Password!";
        Localization["Female"] = "Female";
        //Localization["Functional Issues"] = "Funktionelles Problem";
        Localization["High"] = "High";
        Localization["House Holder"] = "House holder";
        Localization["In_Process"] = "In Process";
        Localization["In Process"] = "In Process";
        Localization["Inbox"] = "Inbox";
        Localization["Login Page"] = "Login Page";
        Localization["Low"] = "Low";
        Localization["Male"] = "Male ";
        Localization["Mr."] = "Mr.";
        Localization["Mrs."] = "Mrs.";
        Localization["New"] = "New";
        Localization["Normal"] = "Normal";
        Localization["Others"] = "Others";
        Localization["Pause"] = "Pause";
        Localization["Parked"] = "Parked";
        Localization["Re-Opened"] = "Re-Opened";
        Localization["Resident"] = "Resident";
        Localization["Resolved"] = "Resolved";
        Localization["Resume"] = "Resume";
        Localization["Several Houses"] = "Several Houses";
        Localization["Single Room"] = "Single Room";
        //Localization["Tecnical Issues"] = "Tecnical Issues";
        Localization["Technicians"] = "Technicians";
        Localization["Technician Detail"] = "Technician";
        Localization["Technician Ticket"] = "Technician";
        Localization["Third Party"] = "Third Party";
        Localization["Third Party Resident"] = "Third Party Resident";
        Localization["Ticket Detail"] = "Ticket";
        Localization["Tickets/Issues"] = "Tickets";
        Localization["Total Resolved Tickets"] = "Total Resolved Tickets";
        Localization["Total Tickets"] = "Total Tickets";
        Localization["User Profile"] = "User Profile";
        Localization["Whole House"] = "Whole House";
        //Ticket Categories///
        Localization["SignalDisplay"] = "NE 2 - Signal Display";
        Localization["SignalFeed"] = "NE 3 - Signal Feed";
        Localization["CableSystem"] = "NE 4 - Cable System";
        Localization["EndCustomer"] = "NE 5 - End Customer";
        //analytic//
        Localization["This Month"] = "This Month";
        Localization["Last Month"] = "Last Month";
        Localization["This Year"] = "This Year";
        Localization["Last Year"] = "Last Year";

        Localization["Company"] = "Company";
}

switch ($("#LanguageSelectBox").val()) {
    case "de":
        LocalizationToast["SendMailMessageType3"] = "Kein Benutzer gefunden mit dem angegebenen Benutzernamen! Bitte versuche es erneut.";
        LocalizationToast["SendMailMessageType2"] = "Kein Benutzer gefunden mit dem angegebenen Benutzernamen! Bitte versuche es erneut.";
        LocalizationToast["SendMailMessageType1"] = "Ihr Passwort wurde erfolgreich zurückgesetzt. Bitte überprüfen Sie Ihre E-Mail.";
        LocalizationToast["SendMailError"] = "Beim Zurücksetzen des Kennworts ist ein Fehler aufgetreten.";
        LocalizationToast["ErrorDeleteingTicket"] = "Fehler beim Löschen des Tickets.";
        LocalizationToast["ErrorDeleteingTechnician"] = "Fehler beim Löschen des Techniker.";
        LocalizationToast["ErrorDeleteingCustomer"] = "Fehler beim Löschen des Kunden.";
        LocalizationToast["AgentDeletedSuccessfully"] = "Agent erfolgreich gelöscht.";
        LocalizationToast["TicketDeletedSuccessfully"] = "Ticket erfolgreich gelöscht.";
        LocalizationToast["TechnicianPasswordResetSuccessfully"] = "Techniker-Passwort erfolgreich zurückgesetzt";
        LocalizationToast["CustomerDeletedSuccessfully"] = "Kunden erfolgreich gelöscht.";
        LocalizationToast["TechnicianDeletedSuccessfully"] = "Techniker erfolgreich gelöscht.";
        LocalizationToast["ErrorDeleteingAttachment"] = "Fehler beim Löschen der Anhang aufgetreten.";
        LocalizationToast["AttachmentDeleted"] = "Anhang gelöscht.";
        LocalizationToast["StatusUpdatedSuccessfully"] = "Status wurde erfolgreich aktualisiert.";
        LocalizationToast["AttachmentUploadedSuccessfully"] = "Anhang erfolgreich hochgeladen."
        LocalizationToast["ErroruploadingAttachment"] = "Beim Hochladen des Dokuments ist ein Fehler aufgetreten.";
        LocalizationToast["ErrorChangingTicketStatus"] = "Beim Ändern des Ticketstatus ist ein Fehler aufgetreten.";
        LocalizationToast["ErrorWhileUpload"] = "Beim Upload ist ein Fehler aufgetreten.";
        LocalizationToast["ErrorTicketAlreadyclosed"] = "Der Ticketstatus kann nicht geändert werden, da er bereits geschlossen ist. Stellen Sie eine Anfrage um das Ticket wieder zu eröffnen.";
        LocalizationToast["ErrrorTicketNotAssigned"] = "Ticketstatus Kann nicht geändert werden, da er niemandem zugewiesen ist."
        LocalizationToast["ErrorLastTicketStatusNotFound"] = "Letzter Ticketstatus nicht gefunden";
        LocalizationToast["ErrorRetriveingTicketStatistics"] = "Beim Abrufen von Ticketstatistiken ist ein Fehler aufgetreten.";
        LocalizationToast["ErrorRetriveingWidgetStatistics"] = "Beim Abrufen von Widget-Statistiken ist ein Fehler aufgetreten.";
        LocalizationToast["ErrorRetriveingCustomerInfo"] = "Bei der Rücknahme von Kundendaten ist ein Fehler aufgetreten.";
        LocalizationToast["CustomersUploadedSuccessfully"] = "Kunde wurde erfolgreich hochgeladen";
        LocalizationToast["GeneralInfoSavedSuccessfully"] = "Allgemeine Info erfolgreich gespeichert.";
        LocalizationToast["CarInfoSavedSuccessfully"] = "Car Info erfolgreich gespeichert.";
        LocalizationToast["ErrorSavingGeneralInfo"] = "Beim Speichern der allgemeinen Informationen ist ein Fehler aufgetreten. ";
        LocalizationToast["ErrorSavingCarInfo"] = "Beim Speichern der car Informationen ist ein Fehler aufgetreten. ";
        LocalizationToast["ContactInfoSavedSuccessfully"] = "Kontaktinformationen erfolgreich gespeichert.";
        LocalizationToast["ErrorSavingContactInfo"] = "Beim Speichern von Kontaktinformationen ist ein Fehler aufgetreten.";
        LocalizationToast["AddressInfoSavedSuccessfully"] = "Adressinformation wurde erfolgreich gespeichert.";
        LocalizationToast["ErrorSavingAddressInfo"] = "Beim Speichern der Adressinformationen ist ein Fehler aufgetreten.";
        LocalizationToast["ErrorRetriveingRecentTicket"] = "Bei der Rücknahme neuer Tickets ist ein Fehler aufgetreten.";
        LocalizationToast["ErrorRetriveingTechnicianInfo"] = "Es ist ein Fehler aufgetreten, beim zurückfordern der Technikerinformationen";
        LocalizationToast["PasswordChangedSuccessfully"] = "Ihr Passwort wurde erfolgreich geändert.";
        LocalizationToast["ErrorPasswordChange"] = "Beim Ändern Ihres Passworts ist ein Fehler aufgetreten! Bitte versuche Sie es erneut.";
        LocalizationToast["ErrorRetriveingProfileInfo"] = "Beim Abrufen von Profilinformationen ist ein Fehler aufgetreten! Bitte versuche Sie es erneut.";
        LocalizationToast["TicketAddedSuccessfully"] = "Ticket Erfolgreich hinzugefügt.";
        LocalizationToast["ErrorAddingTicket"] = "Beim Hinzufügen vom Ticket ist ein Fehler aufgetreten.";
        LocalizationToast["TicketAssignedSuccessfully"] = "Ticket erfolgreich zugewiesen.";
        LocalizationToast["ErrorAssigningTicket"] = "Bei der Zuweisung des Tickets ist ein Fehler aufgetreten.";
        LocalizationToast["UploadedSuccessfully"] = "Erfolgreich hochgeladen.";
        LocalizationToast["TechnicianEmailNotAvailable"] = "Diese E-Mail existiert bereits. Bitte verwenden Sie eine andere E-Mail-ID.";
        LocalizationToast["SelectTicketBeforAssign"] = "Wählen Sie einen Ticket bevor Sie es zuweisen.";
        LocalizationToast["TicketAssignNotAllowPastTime"] = "Nicht erlaubt! Bitte eine Zeit in der Zukunft wählen.";
        LocalizationToast["PageError"] = "Die Seite funktioniert nicht.";
        LocalizationToast["AgentCreateSuccess"] = "Agent erfolgreich erstellt.";
        LocalizationToast["SubAgentCreateSuccessfully"] = "SubAgent erfolgreich gespeichert " ;
        LocalizationToast["CompanySaveSuccessfully"] = "Sub Unternehmen erfolgreich gespeichert ";
        LocalizationToast["SubAgentDeletedSuccessfully"] = "SubAgent erfolgreich gelöscht.";
        LocalizationToast["SubAgentSaveSuccessfully"] = "SubAgent erfolgreich gespeichert";
        LocalizationToast["Zipcodesavesuccessfully"] = "Zipcode erfolgreich gespeichert.";
        LocalizationToast["ErrorinZipcode"] = "Fehler in der Postleitzahl.";


        break;
    default:
        LocalizationToast["SendMailMessageType3"] = "No user found with provided user name! Please try again.";
        LocalizationToast["SendMailMessageType2"] = "No user found with provided user name! Please try again.";
        LocalizationToast["SendMailMessageType1"] = "Your password has been reset successfully. Please check your email.";
        LocalizationToast["SendMailError"] = "An error occured while reseting password.";
        LocalizationToast["AgentDeletedSuccessfully"] = "Agent Deleted Successfully.";
        LocalizationToast["TicketDeletedSuccessfully"] = "Ticket Deleted Successfully.";
        LocalizationToast["CustomerDeletedSuccessfully"] = "Customer Deleted Successfully.";
        LocalizationToast["TechnicianDeletedSuccessfully"] = "Technician Deleted Successfully.";
        LocalizationToast["TechnicianPasswordResetSuccessfully"] = "Technician Password Reset SuccessFully";
        LocalizationToast["ErrorDeleteingTicket"] = "Error Occured while deleting Ticket.";
        LocalizationToast["ErrorDeleteingTechnician"] = "Error Occured while deleting Technician.";
        LocalizationToast["ErrorDeleteingCustomer"] = "Error Occured while deleting Customer.";
        LocalizationToast["ErrorDeleteingAttachment"] = "Error Occured while deleting Attachment.";
        LocalizationToast["AttachmentDeleted"] = "Attachment Deleted.";
        LocalizationToast["StatusUpdatedSuccessfully"] = "Status Updated Successfully";
        LocalizationToast["AttachmentUploadedSuccessfully"] = "Attachment Uploaded Successfully."
        LocalizationToast["ErroruploadingAttachment"] = "Error Occurred While uploading Attachment";
        LocalizationToast["ErrorChangingTicketStatus"] = "An error occured while changing ticket status.";
        LocalizationToast["ErrorWhileUpload"] = "An error occurred while Upload.";
        LocalizationToast["ErrorTicketAlreadyclosed"] = "Ticket status cannot be changed as it is already closed. Request for ticket to reopen.";
        LocalizationToast["ErrrorTicketNotAssigned"] = "Ticket Status Cannot be changed as it is not assigned to anyone."
        LocalizationToast["ErrorLastTicketStatusNotFound"] = "Last ticket status not found .";
        LocalizationToast["ErrorRetriveingTicketStatistics"] = "An error occured while retriveing ticket statistics.";
        LocalizationToast["ErrorRetriveingWidgetStatistics"] = "An error occured while retriveing widget statistics.";
        LocalizationToast["ErrorRetriveingCustomerInfo"] = "An error occured while while retriveing customer info.";
        LocalizationToast["CustomersUploadedSuccessfully"] = "Customers Uploaded Successfully";
        LocalizationToast["GeneralInfoSavedSuccessfully"] = "General Info Saved Successfully.";
        LocalizationToast["CarInfoSavedSuccessfully"] = "Car Info Saved Successfully.";
        LocalizationToast["ErrorSavingGeneralInfo"] = "An error occured while saving general info.";
        LocalizationToast["ErrorSavingCarInfo"] = "An error occured while saving car info.";
        LocalizationToast["ContactInfoSavedSuccessfully"] = "Contact Info Saved Successfully.";
        LocalizationToast["ErrorSavingContactInfo"] = "An error occured while saving contact info.";
        LocalizationToast["AddressInfoSavedSuccessfully"] = "Address Info Saved Successfully.";
        LocalizationToast["ErrorSavingAddressInfo"] = "An error occured while saving address info.";
        LocalizationToast["ErrorRetriveingRecentTicket"] = "An error occured while retriveing recent tickets.";
        LocalizationToast["ErrorRetriveingTechnicianInfo"] = "An error occured while while retriveing technician info.";
        LocalizationToast["PasswordChangedSuccessfully"] = "Your password has been changed successfully.";
        LocalizationToast["ErrorPasswordChange"] = "An error occured while changing your password! Please try again.";
        LocalizationToast["ErrorRetriveingProfileInfo"] = "An error occured while retriveing profile info! Please try again.";
        LocalizationToast["TicketAddedSuccessfully"] = "Ticket Added Successfully.";
        LocalizationToast["ErrorAddingTicket"] = "An error occured while adding ticket.";
        LocalizationToast["TicketAssignedSuccessfully"] = "Ticket Assigned Successfully";
        LocalizationToast["ErrorAssigningTicket"] = "An error occured while assigning ticket.";
        LocalizationToast["UploadedSuccessfully"] = "Uploaded Successfully.";
        LocalizationToast["TechnicianEmailNotAvailable"] = "This email already exist. Please use a different email id.";
        LocalizationToast["SelectTicketBeforAssign"] = "Please select a ticket before assign.";
        LocalizationToast["TicketAssignNotAllowPastTime"] = "You are selecting past time! Please select future time.";
        LocalizationToast["PageError"] = "The page does not work.";
        LocalizationToast["AgentCreateSuccess"] = "Agent created successfully.";
        LocalizationToast["SubAgentCreateSuccessfully"] = "SubAgent Create Successfully";
        LocalizationToast["CompanySaveSuccessfully"] = "Company Save Successfully ";
        LocalizationToast["SubAgentDeletedSuccessfully"] = "SubAgent Deleted Successfully";
        LocalizationToast["SubAgentSaveSuccessfully"] = "SubAgent Save Successfully";
        LocalizationToast["Zipcodesavesuccessfully"] = "Zipcode Save Successfully";
        LocalizationToast["ErrorinZipcode"] = "Error in Zipcode";

}

